### ISSUE TITLE
Battery Percentage Icon Disappearing

### ISSUE THREAD

**Issue by nitinp420** [soleon/Percentage#51] opened 2024-12-29 02:30 UTC
The battery percentage icon disappears automatically after some time. This issue started occurring after a recent Windows update. Upon checking the Event Viewer, I found the following error:

Error	28-12-2024 07:52:07 PM	.NET Runtime	1026	None

Log Name:      Application
Source:        Application Error
Date:          28-12-2024 07:52:07 PM
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          ASUS\nitin
Computer:      ASUS
Description:
Faulting application name: Percentage.App.exe, version: 1.0.0.0, time stamp: 0x67200000
Faulting module name: KERNELBASE.dll, version: 10.0.26100.2454, time stamp: 0x398a1cce
Exception code: 0xe0434352
Fault offset: 0x00000000000c837a
Faulting process id: 0x4E18
Faulting application start time: 0x1DB5919A9011BE2
Faulting application path: C:\Program Files\WindowsApps\61867SoleonInnovation.BatteryPercentageIcon_2.1.4.0_x64__d1gx98zh1khh8\App\Percentage.App.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 970e4df7-89c5-4a29-8262-1df0750a5b59
Faulting package full name: 61867SoleonInnovation.BatteryPercentageIcon_2.1.4.0_x64__d1gx98zh1khh8
Faulting package-relative application ID: App
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-12-28T14:22:07.6543364Z" />
    <EventRecordID>2894</EventRecordID>
    <Correlation />
    <Execution ProcessID="7528" ThreadID="1284" />
    <Channel>Application</Channel>
    <Computer>ASUS</Computer>
    <Security UserID="S-1-5-21-2503008558-484106642-651184624-1001" />
  </System>
  <EventData>
    <Data Name="AppName">Percentage.App.exe</Data>
    <Data Name="AppVersion">1.0.0.0</Data>
    <Data Name="AppTimeStamp">67200000</Data>
    <Data Name="ModuleName">KERNELBASE.dll</Data>
    <Data Name="ModuleVersion">10.0.26100.2454</Data>
    <Data Name="ModuleTimeStamp">398a1cce</Data>
    <Data Name="ExceptionCode">e0434352</Data>
    <Data Name="FaultingOffset">00000000000c837a</Data>
    <Data Name="ProcessId">0x4e18</Data>
    <Data Name="ProcessCreationTime">0x1db5919a9011be2</Data>
    <Data Name="AppPath">C:\Program Files\WindowsApps\61867SoleonInnovation.BatteryPercentageIcon_2.1.4.0_x64__d1gx98zh1khh8\App\Percentage.App.exe</Data>
    <Data Name="ModulePath">C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data Name="IntegratorReportId">970e4df7-89c5-4a29-8262-1df0750a5b59</Data>
    <Data Name="PackageFullName">61867SoleonInnovation.BatteryPercentageIcon_2.1.4.0_x64__d1gx98zh1khh8</Data>
    <Data Name="PackageRelativeAppId">App</Data>
  </EventData>
</Event>

Error	28-12-2024 07:52:07 PM	Application Error	1000	Application Crashing Events

Log Name:      Application
Source:        Application Error
Date:          28-12-2024 07:52:07 PM
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          ASUS\nitin
Computer:      ASUS
Description:
Faulting application name: Percentage.App.exe, version: 1.0.0.0, time stamp: 0x67200000
Faulting module name: KERNELBASE.dll, version: 10.0.26100.2454, time stamp: 0x398a1cce
Exception code: 0xe0434352
Fault offset: 0x00000000000c837a
Faulting process id: 0x4E18
Faulting application start time: 0x1DB5919A9011BE2
Faulting application path: C:\Program Files\WindowsApps\61867SoleonInnovation.BatteryPercentageIcon_2.1.4.0_x64__d1gx98zh1khh8\App\Percentage.App.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 970e4df7-89c5-4a29-8262-1df0750a5b59
Faulting package full name: 61867SoleonInnovation.BatteryPercentageIcon_2.1.4.0_x64__d1gx98zh1khh8
Faulting package-relative application ID: App
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-12-28T14:22:07.6543364Z" />
    <EventRecordID>2894</EventRecordID>
    <Correlation />
    <Execution ProcessID="7528" ThreadID="1284" />
    <Channel>Application</Channel>
    <Computer>ASUS</Computer>
    <Security UserID="S-1-5-21-2503008558-484106642-651184624-1001" />
  </System>
  <EventData>
    <Data Name="AppName">Percentage.App.exe</Data>
    <Data Name="AppVersion">1.0.0.0</Data>
    <Data Name="AppTimeStamp">67200000</Data>
    <Data Name="ModuleName">KERNELBASE.dll</Data>
    <Data Name="ModuleVersion">10.0.26100.2454</Data>
    <Data Name="ModuleTimeStamp">398a1cce</Data>
    <Data Name="ExceptionCode">e0434352</Data>
    <Data Name="FaultingOffset">00000000000c837a</Data>
    <Data Name="ProcessId">0x4e18</Data>
    <Data Name="ProcessCreationTime">0x1db5919a9011be2</Data>
    <Data Name="AppPath">C:\Program Files\WindowsApps\61867SoleonInnovation.BatteryPercentageIcon_2.1.4.0_x64__d1gx98zh1khh8\App\Percentage.App.exe</Data>
    <Data Name="ModulePath">C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data Name="IntegratorReportId">970e4df7-89c5-4a29-8262-1df0750a5b59</Data>
    <Data Name="PackageFullName">61867SoleonInnovation.BatteryPercentageIcon_2.1.4.0_x64__d1gx98zh1khh8</Data>
    <Data Name="PackageRelativeAppId">App</Data>
  </EventData>
</Event>

**Comment by soleon** [comment] 2024-12-29 06:41
Hi @nitinp420 thank you for reporting this issue.

This should be caused by the same `COMException` reported in issue #35, which I have already fixed in version [2.1.5](https://github.com/soleon/Percentage/releases/tag/2.1.5).

It should be available in the Microsoft Store soon.

**Closed** 2024-12-30 12:46 UTC
Labels: bug
